server {
    listen 80;
    server_name _;

    # Пишемо лог запитів
    access_log /var/log/nginx/mywebapp_access.log;
    error_log /var/log/nginx/mywebapp_error.log;

    # Дозволяємо кореневий ендпоінт
    location = / {
        proxy_pass http://127.0.0.1:5200;
    }

    # Дозволяємо ендпоінти бізнес-логіки та перевірки стану
    location /items {
        proxy_pass http://127.0.0.1:5200;
    }
    
    location /health/ {
        proxy_pass http://127.0.0.1:5200;
    }

    # Блокуємо будь-які інші шляхи
    location / {
        return 404;
    }
}